#!/bin/sh
#
# growthplot -- plot the fetchmail population's growth as a function of time
#

# Get data from the NEWS file
timeseries >/tmp/growthplot$$
grep "^[0-9]" /tmp/growthplot$$ >/tmp/growthnumbers$$
grep "^[0-9.]*.[05].0	" /tmp/growthplot$$ >/tmp/growthmajors$$
sed '/^4.2.9/,$d' </tmp/growthnumbers$$ >/tmp/growthannounce$$

cat >/tmp/growthimage$$ <<EOF
set title "Fetchmail project growth history"
set xlabel 'Days since baseline'
set ylabel 'Participants' 6	# Put it right over the Y axis
set key bottom right box

EOF

# OK, now write the event labels
(
	echo "count=0"
	echo "breakheight=510"
	while read version friends announce total days date
	do
		if [ "$version" = '%' ]
		then
			legend="$friends $announce $total $days $date"
			echo "# Associate $lastday to '$legend'"
			echo "count = count + 1"
			echo "lastday = $lastday - 5"
			echo "lasttotal = $lasttotal"
			echo set arrow \
				from lastday, breakheight \
				to lastday, lasttotal+50 \
				head
			echo "endx = lastday + 50 + count * 25"
			echo "endy = breakheight + 50 + count * 50"
			echo "set arrow \
				from lastday, breakheight to endx, endy nohead"
			echo "set label '$legend' at endx+10, endy"
		else
			lastday=$days
			lasttotal=$total
		fi
	done
) </tmp/growthplot$$ >>/tmp/growthimage$$ 

# OK, now write the major-release labels
(
	while read version friends announce total days date
	do
	    echo "set arrow from $days, $total - 80 to $days, $total - 30 head"
	    echo "set label '$version' at $days - 5, $total - 90"
	done
) </tmp/growthmajors$$ >>/tmp/growthimage$$ 

cat >>/tmp/growthimage$$ <<EOF
# First, plot total participants
plot [] [0:] '/tmp/growthnumbers$$' using 5:4 \
		title "Both lists" with points 3

# Then, plot announce-list only starting from the Julian date of the split
replot '/tmp/growthannounce$$' using 5:3 \
		title "fetchmail-announce" with points 4

# Finally, plot the developer list
replot '/tmp/growthannounce$$' using 5:2 \
		title "fetchmail-friends" with points 2
EOF

echo "pause 9999" >>/tmp/growthimage$$

gnuplot /tmp/growthimage$$

rm -f /tmp/growth*

# The gnuplot drivers for GIF and PNG are deficient.  To capture this image,
# use the xv middle-button grab and save to PNG.
