#!/bin/sh
#
# Mine list sizes from MailMan web interfaces

admin="http://lists.ccil.org/mailman/admin"
list="$1"
tmp="/usr/tmp/listsize.$$"

# First get the login cookie...
curl -s -D $tmp $admin/fetchmail-${list}?adminpw=mypaswrd >/dev/null
# Second gets the actual stat
curl -s -b $tmp $admin/fetchmail-${list}/members \
	| sed -n '/.*(\([0-9][0-9]*\).*/s//\1/p'
# end

