#!/bin/sh

version=`sed -n '/VERSION *= *\(.*\)/s//\1/p' <Makefile`
echo "Uploading fetchmail version ${version}"

if [ $* ]
then
    ../upload $*
else
# First, copy to primary website
dest=esr@${WWWHOST}:${WWWDIR}/fetchmail
scp fetchmail-${version}.tar.gz $dest
scp fetchmail-FAQ.html $dest
scp fetchmail-${version}-1.i386.rpm $dest
scp fetchmail-${version}-1.src.rpm $dest
scp fetchmail-features.html $dest
scp NEWS $dest
scp fetchmail-man.html $dest
scp design-notes.html $dest
scp todo.html $dest
scp testservers.html $dest
# The following things vary seldom
#scp funny.html $dest
#scp fetchmail.png $dest
#scp bighand.png $dest
scp growth.png $dest
scp timeseries $dest
scp growthplot $dest
# The following things vary often
scp checksums $dest
scp index.html $dest
scp history.html $dest
echo "Upload to ${WWWVIRTUAL} complete"

    lftp <<EOF
# Copy to FTP site
open $FTPHOST
cd $FTPDIR/fetchmail
put fetchmail-${version}.tar.gz
put fetchmail-${version}-1.i386.rpm
put fetchmail-${version}-1.src.rpm
close

# Next, upload to Metalab
open -u anonymous,esr@thyrsus.com metalab.unc.edu
cd incoming/Linux 
put fetchmail-${version}.tar.gz
put fetchmail.lsm
put README -o fetchmail.README 
put fetchmail-FAQ.html
put fetchmail-${version}-1.i386.rpm
put fetchmail-${version}-1.src.rpm
close
echo "Upload to Metalab complete"

# Finally, upload the RPMS to Red Hat
open incoming.redhat.com
cd libc6
put fetchmail-${version}-1.i386.rpm
put fetchmail-${version}-1.src.rpm
close
echo "Upload to Red Hat contrib complete"

EOF
    echo "fetchmail uploaded"
fi