#!/bin/sh

version=`sed -n '/VERSION *= *\(.*\)/s//\1/p' <Makefile`
echo "Uploading fetchmail version ${version}"

if [ $* ]
then
    ../upload $*
else
    lftp <<EOF
# First, copy to primary website
open ${WWWHOST}
cd ${WWWDIR}/fetchmail
put fetchmail-${version}.tar.gz
put fetchmail-FAQ.html
put fetchmail-${version}-1.i386.rpm
put fetchmail-${version}-1.src.rpm
put fetchmail-features.html
put NEWS
put design-notes.html
#put funny.html
#put fetchmail.gif
#put bighand.gif
put index.html

# Next, upload to the ftp site
open locke.ccil.org
cd ~ftp/pub/esr/fetchmail
put fetchmail-${version}.tar.gz
put fetchmail-${version}-1.i386.rpm
put fetchmail-${version}-1.src.rpm
put README
put FAQ
put FEATURES
close

# Next, upload to Sunsite
open -u anonymous,esr@thyrsus.com metalab.unc.edu
cd incoming/Linux 
put fetchmail-${version}.tar.gz
put fetchmail.lsm
put README -o fetchmail.README 
put fetchmail-FAQ.html
put fetchmail-${version}-1.i386.rpm
put fetchmail-${version}-1.src.rpm
close
 
# Finally, upload the RPMS to Red Hat
open incoming.redhat.com
cd libc6
put fetchmail-${version}-1.i386.rpm
put fetchmail-${version}-1.src.rpm
close

EOF
    echo "fetchmail uploaded"
fi