#!/bin/sh

version=`sed -n '/VERSION *= *\(.*\)/s//\1/p' <Makefile`
echo "Uploading fetchmail version ${version}"

if [ $* ]
then
    ../upload $*
else

echo "Beginning web upload..."
# First, copy to primary website
dest=esr@${WWWHOST}:${WWWDIR}/fetchmail
scp fetchmail-${version}.tar.gz.asc $dest
#scp funny.html $dest
#scp fetchmail.png $dest
#scp bighand.png $dest
scp growth.png $dest
scp timeseries $dest
scp growthplot $dest
scp checksums $dest
# shipper does the rest.
rm -f ANNOUNCE.FRESHMEAT
shipper


