#!/bin/sh

echo >&2 "this script $0 is outdated. Abort."
exit 1

version=`sed -n '/VERSION *= *\(.*\)/s//\1/p' <Makefile`
echo "Uploading fetchmail version ${version} FAQ"

if [ $* ]
then
    ../upload $*
else
    lftp <<EOF
# First, copy to primary website
open ${WWWHOST}
cd ${WWWDIR}/fetchmail
put fetchmail-FAQ.html
close

# Next, upload to the ftp site
open locke.ccil.org
cd ~ftp/pub/esr/fetchmail
put FAQ
close
EOF
    echo "fetchmail FAQ uploaded"
fi
